import { v4 as uuidv4 } from 'uuid'

enum TagOrigemEnum {
  FREELA = 'Freela',
  BORACODAR = 'BoraCodar',
  IGNITE = 'Ignite',
  IDEA = 'Idea',
  NLW = 'NextLevelWeek',
}

enum TagServer {
  GITHUB_PAGES = 'Github Pages',
  VERCEL = 'Vercel',
}

enum TagHardSkill {
  REACT = 'React',
  NEXT = 'NextJS',
  NODE = 'NodeJS',
  TYPESCRIPT = 'Typescript',
  ESLINT = 'ESLint',
  PRETTIER = 'Prettier',
  JEST = 'Jest',
  VITE = 'Vite',
  STYLED_COMPONENTS = 'Styled Components',
}

export const projects = [
  {
    title: 'IG News',
    date: '2023-01-02',
    description: '',
    image: '',
    tags: [TagOrigemEnum.IGNITE],
    source: 'https://github.com/tuliooov/ignite-reactjs-desafios-deploy-ignews',
    id: uuidv4(),
  },
  {
    title: 'Uploading Images',
    date: '2022-09-18',
    description: '',
    image: '',
    tags: [TagOrigemEnum.IGNITE],
    source:
      'https://github.com/tuliooov/ignite-template-reactjs-upload-de-imagens',
    id: uuidv4(),
  },
  {
    title: 'NLW Impulse',
    date: '2022-06-06',
    description: '',
    image: '',
    tags: [TagOrigemEnum.NLW],
    source: 'https://github.com/tuliooov/NLW-8-IMPULSE',
    id: uuidv4(),
  },
  {
    title: 'NLW Esports',
    date: '2022-09-18',
    description: '',
    image: '',
    tags: [TagOrigemEnum.NLW],
    source: 'https://github.com/tuliooov/nlw-esports',
    id: uuidv4(),
  },
  {
    title: 'NLW Copa',
    date: '2022-11-14',
    description: '',
    image: '',
    tags: [TagOrigemEnum.NLW],
    source: 'https://github.com/tuliooov/nlw-copa',
    id: uuidv4(),
  },
  {
    title: 'Professor GPT',
    date: '2023-07-01',
    description: '',
    image: '',
    tags: [TagOrigemEnum.IDEA],
    source: 'https://github.com/tuliooov/professor-chatgpt',
    visit: 'https://professor-chatgpt.vercel.app/',
    id: uuidv4(),
  },
  {
    title: 'BBP',
    date: '2023-06-25',
    description: '',
    image: '',
    tags: [TagOrigemEnum.FREELA],
    id: uuidv4(),
  },
  {
    title: 'Controle de Vendas',
    date: '2023-06-01',
    description: '',
    image: '',
    tags: [TagOrigemEnum.IDEA],
    source: 'https://github.com/tuliooov/sistema-cliente-vendas',
    visit: 'https://sistema-cliente-vendas.vercel.app/',
    id: uuidv4(),
  },
  {
    title: 'Call Design System',
    date: '2023-05-30',
    description: '',
    image: '',
    tags: [TagOrigemEnum.IGNITE],
    source:
      'https://github.com/tuliooov/ignite-2022-project-5-call-design-system',
    // visit: 'https://sistema-cliente-vendas.vercel.app/',
    id: uuidv4(),
  },
  {
    title: 'SpaceTime',
    date: '2023-05-24',
    description: '',
    image: '',
    tags: [TagOrigemEnum.IGNITE],
    source: 'https://github.com/tuliooov/nlw-12-spacetime-ignite',
    // visit: 'https://sistema-cliente-vendas.vercel.app/',
    id: uuidv4(),
  },
  {
    title: 'Currency Converter',
    date: '2023-04-03',
    description: '',
    image: '',
    tags: ['BoraCodar'],
    source: 'https://github.com/tuliooov/boracodar-9-conversor-de-moedas',
    id: uuidv4(),
  },
  {
    title: 'Mv Tecidos Instucional',
    date: '2021-01-01',
    description: '',
    image: '',
    tags: [TagOrigemEnum.FREELA],
    source: 'https://github.com/tuliooov/site-institucional-mv-tecidos',
    id: uuidv4(),
  },
  {
    title: 'My Portfolio',
    date: '2023-04-03',
    description: '',
    image: '',
    tags: [TagOrigemEnum.IDEA],
    source: 'https://github.com/tuliooov/my-portfolio',
    id: uuidv4(),
  },
  {
    title: 'Github Blog',
    date: '2023-04-03',
    description: '',
    image: '',
    tags: [TagOrigemEnum.IGNITE],
    source: 'https://github.com/tuliooov/github-blog',
    id: uuidv4(),
  },
  {
    title: 'Photo Shop',
    date: '2023-04-03',
    description: '',
    image: '',
    tags: [TagOrigemEnum.IGNITE],
    source: 'https://github.com/tuliooov/photos-shop',
    id: uuidv4(),
  },
  {
    title: 'Dashboard Page',
    date: '2023-04-03',
    description: '',
    image: '',
    tags: ['BoraCodar'],
    source: 'https://github.com/tuliooov/boracodar-8-pagina-de-dashboard',
    id: uuidv4(),
  },
  {
    title: 'Search Of Carnival ',
    date: '2023-04-03',
    description: '',
    image: '',
    tags: ['BoraCodar'],
    source:
      'https://github.com/tuliooov/boracodar-7-site-para-encontrar-bloco-de-carnaval',
    id: uuidv4(),
  },
  {
    title: 'Ticket Component',
    date: '2023-04-03',
    description: '',
    image: '',
    tags: ['BoraCodar'],
    source:
      'https://github.com/tuliooov/boracodar6-componente-de-cartao-de-embarque',
    id: uuidv4(),
  },
  {
    title: 'Weather Page',
    date: '2023-04-03',
    description: '',
    image: '',
    tags: ['BoraCodar'],
    source: 'https://github.com/tuliooov/boracodar-10-pagina-de-clima',
    id: uuidv4(),
  },
  {
    title: 'Login Page',
    date: '2023-04-03',
    description: '',
    image: '',
    tags: ['BoraCodar'],
    source: 'https://github.com/tuliooov/boracodar-11-uma-pagina-de-login',
    id: uuidv4(),
  },
  {
    title: 'Kanban Page',
    date: '2023-04-03',
    description: '',
    image: '',
    tags: ['BoraCodar'],
    source: 'https://github.com/tuliooov/boracodar-12-pagina-de-kanban',
    id: uuidv4(),
  },
  {
    title: 'Card Payment',
    date: '2023-04-03',
    description: '',
    image: '',
    tags: ['BoraCodar'],
    source:
      'https://github.com/tuliooov/boracodar-13-formulario-de-cartao-de-credito',
    id: uuidv4(),
  },
  {
    title: 'Upload Component',
    date: '2023-04-03',
    description: '',
    image: '',
    tags: ['BoraCodar'],
    source: 'https://github.com/tuliooov/boracodar-14-componente-de-upload',
    id: uuidv4(),
  },
  {
    title: 'Price Table',
    date: '2023-04-03',
    description: '',
    image: '',
    tags: ['BoraCodar'],
    source: 'https://github.com/tuliooov/boracodar-15-tabela-de-preco',
    id: uuidv4(),
  },
  {
    title: 'Contacts Page',
    date: '2023-05-9',
    description: '',
    image: '',
    tags: ['BoraCodar'],
    source: 'https://github.com/tuliooov/boracodar-16-pagina-de-contatos',
    // visit: 'https://sistema-cliente-vendas.vercel.app/',
    id: uuidv4(),
  },
  {
    title: 'Calculator #BoraCoda',
    date: '2023-02-09',
    description: 'Develop a desktop calculator, which can be responsive.',
    image: './images/calculator-05.png',
    tags: [
      'BoraCodar',
      'NextJS',
      'Style Components',
      'Typescript',
      'Github Pages',
      'ESlint',
      'Color Scheme CSS',
    ],
    source: 'https://github.com/tuliooov/calculator-challenge-5-bora-codar',
    visit: 'https://tuliooov.github.io/calculator-challenge-5-bora-codar/',
    id: uuidv4(),
  },
  {
    title: 'DT Money 2.0',
    date: '2023-02-06',
    description:
      'Vimos como performar aplicações com o React entendendo como funcionam os algoritmos internos da biblioteca e todo fluxo de renderização de componentes.',
    image: './images/dt-money.png',
    tags: [
      TagOrigemEnum.IGNITE,
      'ViteJS',
      'Style Components',
      'Typescript',
      'Github Pages',
      'JSON-server',
      'Radix UI',
      'Use-context-selector',
      'React-Hook-Forms',
    ],
    source: 'https://github.com/tuliooov/ignite-2022-project-2-dt-money',
    visit: 'https://tuliooov.github.io/ignite-2022-project-2-dt-money/',
    id: uuidv4(),
  },
  {
    title: 'Chat',
    date: '2023-01-28',
    description:
      'Develop a desktop chat, which can be responsive. You can go further and add animations, or even implement a functional chat.',
    image: './images/chat.png',
    tags: [
      'BoraCodar',
      'NextJS',
      'CSS Modules',
      'Typescript',
      'Github Pages',
      'ESLint',
      'React Icons',
      'Date Fns',
    ],
    source: 'https://github.com/tuliooov/one-chat-challenge-4-bora-codar',
    visit: 'https://tuliooov.github.io/one-chat-challenge-4-bora-codar/',
    id: uuidv4(),
  },
  {
    title: 'Buttons and Cursors',
    date: '2023-01-28',
    description:
      'Each button variant follows an interface that dictates what a button within the application accepts to receive as a property.',
    image: './images/buttons-and-cursors.png',
    tags: ['BoraCodar', 'Vite', 'CSS', 'Typescript', 'Github Pages'],
    source: 'https://github.com/tuliooov/botoes-e-cursores-bora-codar',
    visit: 'https://tuliooov.github.io/botoes-e-cursores-bora-codar/',
    id: uuidv4(),
  },
  {
    title: 'Coffee Delivery',
    date: '2023-01-27',
    description:
      'During this challenge, we used slightly more advanced concepts developing a coffee ordering application from scratch!',
    image: './images/coffee-delivery.png',
    tags: [
      TagOrigemEnum.IGNITE,
      'Vite',
      'Styled Comp.',
      'Typescript',
      'Context API',
      'Local Storage',
      'Router Dom',
      'ReactHookForm',
      'Formulário',
      'Github Pages',
    ],
    source:
      'https://github.com/tuliooov/ignite-2022-reactjs-coffee-challenge-02-delivery',
    visit:
      'https://tuliooov.github.io/ignite-2022-reactjs-coffee-challenge-02-delivery/',
    id: uuidv4(),
  },
  {
    title: 'Ignite Timer',
    date: '2023-01-25',
    description:
      'We built a complete application with routing and several important concepts of the React ecosystem.',
    image: './images/ignite-timer.png',
    tags: [
      TagOrigemEnum.IGNITE,
      'Vite',
      'Styled Comp.',
      'Typescript',
      'Local Storage',
      'Router Dom',
      'Immer',
      'ReactHookForm',
      'Formulário',
      'Github Pages',
    ],
    source: 'https://github.com/tuliooov/02-ignite-timer',
    visit: 'https://tuliooov.github.io/02-ignite-timer/',
    id: uuidv4(),
  },
  {
    title: 'ToDo List',
    date: '2023-01-06',
    description: 'We reinforce the most important concepts of ReactJS.',
    image: './images/to-do-list.png',
    tags: ['Vite', 'Typescript', 'Local Storage', 'Github Pages'],
    source:
      'https://github.com/tuliooov/Ignite-ReactJS-Desafio-01-Praticando-os-conceitos-do-ReactJS',
    visit:
      'https://tuliooov.github.io/Ignite-ReactJS-Desafio-01-Praticando-os-conceitos-do-ReactJS/',
    id: uuidv4(),
  },
]

export const TimeLineData = [
  { year: 2024, text: 'I hope to return and finish my graduation.' },
  { year: 2023, text: 'I will carry out my first exchange for studies.' },
  { year: 2022, text: 'Discovered the importance of speaking English.' },
  { year: 2021, text: 'Got an amazing job at Banco Inter.' },
  { year: 2020, text: 'Developed several incredible tools for Cliente Fiel.' },
  { year: 2020, text: 'Started my degree in Computer Science at PUC - Minas.' },
  {
    year: 2019,
    text: 'Started studying at RocketSeat, where I study until today.',
  },
  { year: 2018, text: 'Developed tools for the company MV Tecidos.' },
  { year: 2017, text: 'Started my job at Cliente Fiel.' },
  { year: 2016, text: 'My first job, in a Casa Art Festas online store.' },

  { year: 2016, text: 'Completed high school.' },
  {
    year: 2015,
    text: 'Started studying HTML, CSS and JS in the PRONATEC course.',
  },
  { year: 2013, text: 'Graduated from elementary school.' },
]
